//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CallEntries struct {
	CallID         int32 `sql:"primary_key"`
	RegistrationID int32 `sql:"primary_key"`
	Kind           string
	Semester       int32
	Outcome        string
	WantsPromotion int32
}
