//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Candidates struct {
	ID           int32 `sql:"primary_key"`
	Cpf          string
	Name         string
	SocialName   string
	Birthdate    string
	Sex          string
	MotherName   string
	AddressLine  string
	AddressLine2 string
	HouseNumber  string
	Neighborhood string
	Municipality string
	State        string
	Cep          string
	Email        string
	Phone1       string
	Phone2       string
}
