//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Courses struct {
	ID           int32 `sql:"primary_key"`
	TimeSlot     string
	QuotaID      int32
	Seats        int32
	MinimumScore int32
}
