//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Registrations struct {
	ID                   int32 `sql:"primary_key"`
	EnrollmentID         string
	CourseID             int32
	Option               int32
	LanguagesScore       int32
	HumanitiesScore      int32
	NaturalSciencesScore int32
	MathematicsScore     int32
	EssayScore           int32
	CompositeScore       int32
	Ranking              int32
	Status               string
	SelectionID          int32
	CallID               *int32
	CandidateID          int32
}
