// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// CallEntryKindInitial is a CallEntryKind of type initial.
	CallEntryKindInitial CallEntryKind = "initial"
	// CallEntryKindWaitlist is a CallEntryKind of type waitlist.
	CallEntryKindWaitlist CallEntryKind = "waitlist"
)

var ErrInvalidCallEntryKind = errors.New("not a valid CallEntryKind")

// String implements the Stringer interface.
func (x CallEntryKind) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CallEntryKind) IsValid() bool {
	_, err := ParseCallEntryKind(string(x))
	return err == nil
}

var _CallEntryKindValue = map[string]CallEntryKind{
	"initial":  CallEntryKindInitial,
	"waitlist": CallEntryKindWaitlist,
}

// ParseCallEntryKind attempts to convert a string to a CallEntryKind.
func ParseCallEntryKind(name string) (CallEntryKind, error) {
	if x, ok := _CallEntryKindValue[name]; ok {
		return x, nil
	}
	return CallEntryKind(""), fmt.Errorf("%s is %w", name, ErrInvalidCallEntryKind)
}

const (
	// CallEntryOutcomePending is a CallEntryOutcome of type pending.
	CallEntryOutcomePending CallEntryOutcome = "pending"
	// CallEntryOutcomeEnrolled is a CallEntryOutcome of type enrolled.
	CallEntryOutcomeEnrolled CallEntryOutcome = "enrolled"
	// CallEntryOutcomeAbsent is a CallEntryOutcome of type absent.
	CallEntryOutcomeAbsent CallEntryOutcome = "absent"
)

var ErrInvalidCallEntryOutcome = errors.New("not a valid CallEntryOutcome")

// String implements the Stringer interface.
func (x CallEntryOutcome) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CallEntryOutcome) IsValid() bool {
	_, err := ParseCallEntryOutcome(string(x))
	return err == nil
}

var _CallEntryOutcomeValue = map[string]CallEntryOutcome{
	"pending":  CallEntryOutcomePending,
	"enrolled": CallEntryOutcomeEnrolled,
	"absent":   CallEntryOutcomeAbsent,
}

// ParseCallEntryOutcome attempts to convert a string to a CallEntryOutcome.
func ParseCallEntryOutcome(name string) (CallEntryOutcome, error) {
	if x, ok := _CallEntryOutcomeValue[name]; ok {
		return x, nil
	}
	return CallEntryOutcome(""), fmt.Errorf("%s is %w", name, ErrInvalidCallEntryOutcome)
}
