// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// CallStatusCalling is a CallStatus of type calling.
	CallStatusCalling CallStatus = "calling"
	// CallStatusDone is a CallStatus of type done.
	CallStatusDone CallStatus = "done"
)

var ErrInvalidCallStatus = errors.New("not a valid CallStatus")

// String implements the Stringer interface.
func (x CallStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CallStatus) IsValid() bool {
	_, err := ParseCallStatus(string(x))
	return err == nil
}

var _CallStatusValue = map[string]CallStatus{
	"calling": CallStatusCalling,
	"done":    CallStatusDone,
}

// ParseCallStatus attempts to convert a string to a CallStatus.
func ParseCallStatus(name string) (CallStatus, error) {
	if x, ok := _CallStatusValue[name]; ok {
		return x, nil
	}
	return CallStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidCallStatus)
}
