// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// CallStatusCalling is a CallStatus of type Calling.
	CallStatusCalling CallStatus = iota
	// CallStatusDone is a CallStatus of type Done.
	CallStatusDone
)

var ErrInvalidCallStatus = errors.New("not a valid CallStatus")

const _CallStatusName = "callingdone"

var _CallStatusMap = map[CallStatus]string{
	CallStatusCalling: _CallStatusName[0:7],
	CallStatusDone:    _CallStatusName[7:11],
}

// String implements the Stringer interface.
func (x CallStatus) String() string {
	if str, ok := _CallStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("CallStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CallStatus) IsValid() bool {
	_, ok := _CallStatusMap[x]
	return ok
}

var _CallStatusValue = map[string]CallStatus{
	_CallStatusName[0:7]:  CallStatusCalling,
	_CallStatusName[7:11]: CallStatusDone,
}

// ParseCallStatus attempts to convert a string to a CallStatus.
func ParseCallStatus(name string) (CallStatus, error) {
	if x, ok := _CallStatusValue[name]; ok {
		return x, nil
	}
	return CallStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidCallStatus)
}
