// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// CoursePeriodMorning is a CoursePeriod of type morning.
	CoursePeriodMorning CoursePeriod = "morning"
	// CoursePeriodEvening is a CoursePeriod of type evening.
	CoursePeriodEvening CoursePeriod = "evening"
)

var ErrInvalidCoursePeriod = errors.New("not a valid CoursePeriod")

// String implements the Stringer interface.
func (x CoursePeriod) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CoursePeriod) IsValid() bool {
	_, err := ParseCoursePeriod(string(x))
	return err == nil
}

var _CoursePeriodValue = map[string]CoursePeriod{
	"morning": CoursePeriodMorning,
	"evening": CoursePeriodEvening,
}

// ParseCoursePeriod attempts to convert a string to a CoursePeriod.
func ParseCoursePeriod(name string) (CoursePeriod, error) {
	if x, ok := _CoursePeriodValue[name]; ok {
		return x, nil
	}
	return CoursePeriod(""), fmt.Errorf("%s is %w", name, ErrInvalidCoursePeriod)
}
