// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// CoursePeriodMorning is a CoursePeriod of type Morning.
	CoursePeriodMorning CoursePeriod = iota
	// CoursePeriodEvening is a CoursePeriod of type Evening.
	CoursePeriodEvening
)

var ErrInvalidCoursePeriod = errors.New("not a valid CoursePeriod")

const _CoursePeriodName = "morningevening"

var _CoursePeriodMap = map[CoursePeriod]string{
	CoursePeriodMorning: _CoursePeriodName[0:7],
	CoursePeriodEvening: _CoursePeriodName[7:14],
}

// String implements the Stringer interface.
func (x CoursePeriod) String() string {
	if str, ok := _CoursePeriodMap[x]; ok {
		return str
	}
	return fmt.Sprintf("CoursePeriod(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x CoursePeriod) IsValid() bool {
	_, ok := _CoursePeriodMap[x]
	return ok
}

var _CoursePeriodValue = map[string]CoursePeriod{
	_CoursePeriodName[0:7]:  CoursePeriodMorning,
	_CoursePeriodName[7:14]: CoursePeriodEvening,
}

// ParseCoursePeriod attempts to convert a string to a CoursePeriod.
func ParseCoursePeriod(name string) (CoursePeriod, error) {
	if x, ok := _CoursePeriodValue[name]; ok {
		return x, nil
	}
	return CoursePeriod(0), fmt.Errorf("%s is %w", name, ErrInvalidCoursePeriod)
}
