// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// RegistrationStatusApproved is a RegistrationStatus of type approved.
	RegistrationStatusApproved RegistrationStatus = "approved"
	// RegistrationStatusWaitlisted is a RegistrationStatus of type waitlisted.
	RegistrationStatusWaitlisted RegistrationStatus = "waitlisted"
	// RegistrationStatusAbsent is a RegistrationStatus of type absent.
	RegistrationStatusAbsent RegistrationStatus = "absent"
	// RegistrationStatusEnrolled is a RegistrationStatus of type enrolled.
	RegistrationStatusEnrolled RegistrationStatus = "enrolled"
	// RegistrationStatusDeclinedPromotion is a RegistrationStatus of type declined_promotion.
	RegistrationStatusDeclinedPromotion RegistrationStatus = "declined_promotion"
)

var ErrInvalidRegistrationStatus = errors.New("not a valid RegistrationStatus")

// String implements the Stringer interface.
func (x RegistrationStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RegistrationStatus) IsValid() bool {
	_, err := ParseRegistrationStatus(string(x))
	return err == nil
}

var _RegistrationStatusValue = map[string]RegistrationStatus{
	"approved":           RegistrationStatusApproved,
	"waitlisted":         RegistrationStatusWaitlisted,
	"absent":             RegistrationStatusAbsent,
	"enrolled":           RegistrationStatusEnrolled,
	"declined_promotion": RegistrationStatusDeclinedPromotion,
}

// ParseRegistrationStatus attempts to convert a string to a RegistrationStatus.
func ParseRegistrationStatus(name string) (RegistrationStatus, error) {
	if x, ok := _RegistrationStatusValue[name]; ok {
		return x, nil
	}
	return RegistrationStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidRegistrationStatus)
}
