// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// RegistrationStatusApproved is a RegistrationStatus of type Approved.
	RegistrationStatusApproved RegistrationStatus = iota
	// RegistrationStatusWaitlisted is a RegistrationStatus of type Waitlisted.
	RegistrationStatusWaitlisted
	// RegistrationStatusAbsent is a RegistrationStatus of type Absent.
	RegistrationStatusAbsent
	// RegistrationStatusEnrolled is a RegistrationStatus of type Enrolled.
	RegistrationStatusEnrolled
)

var ErrInvalidRegistrationStatus = errors.New("not a valid RegistrationStatus")

const _RegistrationStatusName = "approvedwaitlistedabsentenrolled"

var _RegistrationStatusMap = map[RegistrationStatus]string{
	RegistrationStatusApproved:   _RegistrationStatusName[0:8],
	RegistrationStatusWaitlisted: _RegistrationStatusName[8:18],
	RegistrationStatusAbsent:     _RegistrationStatusName[18:24],
	RegistrationStatusEnrolled:   _RegistrationStatusName[24:32],
}

// String implements the Stringer interface.
func (x RegistrationStatus) String() string {
	if str, ok := _RegistrationStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("RegistrationStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x RegistrationStatus) IsValid() bool {
	_, ok := _RegistrationStatusMap[x]
	return ok
}

var _RegistrationStatusValue = map[string]RegistrationStatus{
	_RegistrationStatusName[0:8]:   RegistrationStatusApproved,
	_RegistrationStatusName[8:18]:  RegistrationStatusWaitlisted,
	_RegistrationStatusName[18:24]: RegistrationStatusAbsent,
	_RegistrationStatusName[24:32]: RegistrationStatusEnrolled,
}

// ParseRegistrationStatus attempts to convert a string to a RegistrationStatus.
func ParseRegistrationStatus(name string) (RegistrationStatus, error) {
	if x, ok := _RegistrationStatusValue[name]; ok {
		return x, nil
	}
	return RegistrationStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidRegistrationStatus)
}
