// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// SelectionKindApproved is a SelectionKind of type Approved.
	SelectionKindApproved SelectionKind = iota
	// SelectionKindWaitlist is a SelectionKind of type Waitlist.
	SelectionKindWaitlist
)

var ErrInvalidSelectionKind = errors.New("not a valid SelectionKind")

const _SelectionKindName = "approvedwaitlist"

var _SelectionKindMap = map[SelectionKind]string{
	SelectionKindApproved: _SelectionKindName[0:8],
	SelectionKindWaitlist: _SelectionKindName[8:16],
}

// String implements the Stringer interface.
func (x SelectionKind) String() string {
	if str, ok := _SelectionKindMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SelectionKind(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SelectionKind) IsValid() bool {
	_, ok := _SelectionKindMap[x]
	return ok
}

var _SelectionKindValue = map[string]SelectionKind{
	_SelectionKindName[0:8]:  SelectionKindApproved,
	_SelectionKindName[8:16]: SelectionKindWaitlist,
}

// ParseSelectionKind attempts to convert a string to a SelectionKind.
func ParseSelectionKind(name string) (SelectionKind, error) {
	if x, ok := _SelectionKindValue[name]; ok {
		return x, nil
	}
	return SelectionKind(0), fmt.Errorf("%s is %w", name, ErrInvalidSelectionKind)
}
