// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// SelectionKindApproved is a SelectionKind of type approved.
	SelectionKindApproved SelectionKind = "approved"
	// SelectionKindWaitlist is a SelectionKind of type waitlist.
	SelectionKindWaitlist SelectionKind = "waitlist"
)

var ErrInvalidSelectionKind = errors.New("not a valid SelectionKind")

// String implements the Stringer interface.
func (x SelectionKind) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SelectionKind) IsValid() bool {
	_, err := ParseSelectionKind(string(x))
	return err == nil
}

var _SelectionKindValue = map[string]SelectionKind{
	"approved": SelectionKindApproved,
	"waitlist": SelectionKindWaitlist,
}

// ParseSelectionKind attempts to convert a string to a SelectionKind.
func ParseSelectionKind(name string) (SelectionKind, error) {
	if x, ok := _SelectionKindValue[name]; ok {
		return x, nil
	}
	return SelectionKind(""), fmt.Errorf("%s is %w", name, ErrInvalidSelectionKind)
}
