// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// SemesterStatusOpen is a SemesterStatus of type Open.
	SemesterStatusOpen SemesterStatus = iota
	// SemesterStatusClosed is a SemesterStatus of type Closed.
	SemesterStatusClosed
)

var ErrInvalidSemesterStatus = errors.New("not a valid SemesterStatus")

const _SemesterStatusName = "openclosed"

var _SemesterStatusMap = map[SemesterStatus]string{
	SemesterStatusOpen:   _SemesterStatusName[0:4],
	SemesterStatusClosed: _SemesterStatusName[4:10],
}

// String implements the Stringer interface.
func (x SemesterStatus) String() string {
	if str, ok := _SemesterStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SemesterStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SemesterStatus) IsValid() bool {
	_, ok := _SemesterStatusMap[x]
	return ok
}

var _SemesterStatusValue = map[string]SemesterStatus{
	_SemesterStatusName[0:4]:  SemesterStatusOpen,
	_SemesterStatusName[4:10]: SemesterStatusClosed,
}

// ParseSemesterStatus attempts to convert a string to a SemesterStatus.
func ParseSemesterStatus(name string) (SemesterStatus, error) {
	if x, ok := _SemesterStatusValue[name]; ok {
		return x, nil
	}
	return SemesterStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidSemesterStatus)
}

// MarshalText implements the text marshaller method.
func (x SemesterStatus) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *SemesterStatus) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseSemesterStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *SemesterStatus) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
