// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package types

import (
	"errors"
	"fmt"
)

const (
	// SemesterStatusOpen is a SemesterStatus of type open.
	SemesterStatusOpen SemesterStatus = "open"
	// SemesterStatusClosed is a SemesterStatus of type closed.
	SemesterStatusClosed SemesterStatus = "closed"
)

var ErrInvalidSemesterStatus = errors.New("not a valid SemesterStatus")

// String implements the Stringer interface.
func (x SemesterStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SemesterStatus) IsValid() bool {
	_, err := ParseSemesterStatus(string(x))
	return err == nil
}

var _SemesterStatusValue = map[string]SemesterStatus{
	"open":   SemesterStatusOpen,
	"closed": SemesterStatusClosed,
}

// ParseSemesterStatus attempts to convert a string to a SemesterStatus.
func ParseSemesterStatus(name string) (SemesterStatus, error) {
	if x, ok := _SemesterStatusValue[name]; ok {
		return x, nil
	}
	return SemesterStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidSemesterStatus)
}
