//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var RegistrationPlacements = newRegistrationPlacementsTable("", "registration_placements", "")

type registrationPlacementsTable struct {
	sqlite.Table

	// Columns
	RegistrationID sqlite.ColumnInteger
	CallID         sqlite.ColumnInteger
	Kind           sqlite.ColumnString
	Semester       sqlite.ColumnInteger
	Outcome        sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type RegistrationPlacementsTable struct {
	registrationPlacementsTable

	EXCLUDED registrationPlacementsTable
}

// AS creates new RegistrationPlacementsTable with assigned alias
func (a RegistrationPlacementsTable) AS(alias string) *RegistrationPlacementsTable {
	return newRegistrationPlacementsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RegistrationPlacementsTable with assigned schema name
func (a RegistrationPlacementsTable) FromSchema(schemaName string) *RegistrationPlacementsTable {
	return newRegistrationPlacementsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RegistrationPlacementsTable with assigned table prefix
func (a RegistrationPlacementsTable) WithPrefix(prefix string) *RegistrationPlacementsTable {
	return newRegistrationPlacementsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RegistrationPlacementsTable with assigned table suffix
func (a RegistrationPlacementsTable) WithSuffix(suffix string) *RegistrationPlacementsTable {
	return newRegistrationPlacementsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRegistrationPlacementsTable(schemaName, tableName, alias string) *RegistrationPlacementsTable {
	return &RegistrationPlacementsTable{
		registrationPlacementsTable: newRegistrationPlacementsTableImpl(schemaName, tableName, alias),
		EXCLUDED:                    newRegistrationPlacementsTableImpl("", "excluded", ""),
	}
}

func newRegistrationPlacementsTableImpl(schemaName, tableName, alias string) registrationPlacementsTable {
	var (
		RegistrationIDColumn = sqlite.IntegerColumn("registration_id")
		CallIDColumn         = sqlite.IntegerColumn("call_id")
		KindColumn           = sqlite.StringColumn("kind")
		SemesterColumn       = sqlite.IntegerColumn("semester")
		OutcomeColumn        = sqlite.StringColumn("outcome")
		allColumns           = sqlite.ColumnList{RegistrationIDColumn, CallIDColumn, KindColumn, SemesterColumn, OutcomeColumn}
		mutableColumns       = sqlite.ColumnList{RegistrationIDColumn, CallIDColumn, KindColumn, SemesterColumn, OutcomeColumn}
		defaultColumns       = sqlite.ColumnList{}
	)

	return registrationPlacementsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		RegistrationID: RegistrationIDColumn,
		CallID:         CallIDColumn,
		Kind:           KindColumn,
		Semester:       SemesterColumn,
		Outcome:        OutcomeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
