// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Backup(arg1) {
  return window['go']['main']['App']['Backup'](arg1);
}

export function CloseCall(arg1) {
  return window['go']['main']['App']['CloseCall'](arg1);
}

export function CloseSemester(arg1) {
  return window['go']['main']['App']['CloseSemester'](arg1);
}

export function CreateCall() {
  return window['go']['main']['App']['CreateCall']();
}

export function DeleteApprovedSelection() {
  return window['go']['main']['App']['DeleteApprovedSelection']();
}

export function DeleteCall(arg1) {
  return window['go']['main']['App']['DeleteCall'](arg1);
}

export function DeleteWaitlistSelection() {
  return window['go']['main']['App']['DeleteWaitlistSelection']();
}

export function Destroy() {
  return window['go']['main']['App']['Destroy']();
}

export function EmailPDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EmailPDF'](arg1, arg2, arg3, arg4);
}

export function EnrollmentPDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['EnrollmentPDF'](arg1, arg2, arg3, arg4);
}

export function ExportCSV(arg1) {
  return window['go']['main']['App']['ExportCSV'](arg1);
}

export function FetchApprovedSelection() {
  return window['go']['main']['App']['FetchApprovedSelection']();
}

export function FetchCallEntries(arg1) {
  return window['go']['main']['App']['FetchCallEntries'](arg1);
}

export function FetchCalls() {
  return window['go']['main']['App']['FetchCalls']();
}

export function FetchRegistration(arg1) {
  return window['go']['main']['App']['FetchRegistration'](arg1);
}

export function FetchRegistrations() {
  return window['go']['main']['App']['FetchRegistrations']();
}

export function FetchRegistrationsByCourseID(arg1) {
  return window['go']['main']['App']['FetchRegistrationsByCourseID'](arg1);
}

export function FetchRegistrationsBySelectionID(arg1) {
  return window['go']['main']['App']['FetchRegistrationsBySelectionID'](arg1);
}

export function FetchSemesters() {
  return window['go']['main']['App']['FetchSemesters']();
}

export function FetchWaitlistSelection() {
  return window['go']['main']['App']['FetchWaitlistSelection']();
}

export function LoadApprovedSelection(arg1, arg2) {
  return window['go']['main']['App']['LoadApprovedSelection'](arg1, arg2);
}

export function LoadWaitlistSelection(arg1, arg2) {
  return window['go']['main']['App']['LoadWaitlistSelection'](arg1, arg2);
}

export function OpenCall(arg1) {
  return window['go']['main']['App']['OpenCall'](arg1);
}

export function OpenFileDialog(arg1, arg2, arg3) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2, arg3);
}

export function PreviewCall() {
  return window['go']['main']['App']['PreviewCall']();
}

export function ReopenSemester(arg1) {
  return window['go']['main']['App']['ReopenSemester'](arg1);
}

export function Restore(arg1) {
  return window['go']['main']['App']['Restore'](arg1);
}

export function SaveFileDialog(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFileDialog'](arg1, arg2, arg3, arg4);
}

export function SetCallEntryOutcome(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetCallEntryOutcome'](arg1, arg2, arg3);
}

export function SetWantsPromotion(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetWantsPromotion'](arg1, arg2, arg3);
}

export function TeacherPDF(arg1, arg2, arg3) {
  return window['go']['main']['App']['TeacherPDF'](arg1, arg2, arg3);
}

export function WebsitePDF(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['WebsitePDF'](arg1, arg2, arg3, arg4);
}
