// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Backup(arg1:string):Promise<void>;

export function CloseCall(arg1:number):Promise<void>;

export function CloseSemester(arg1:number):Promise<void>;

export function CreateCall():Promise<void>;

export function DeleteApprovedSelection():Promise<void>;

export function DeleteCall(arg1:number):Promise<void>;

export function DeleteWaitlistSelection():Promise<void>;

export function Destroy():Promise<void>;

export function EmailPDF(arg1:number,arg2:string,arg3:number,arg4:string):Promise<void>;

export function EnrollmentPDF(arg1:number,arg2:string,arg3:number,arg4:string):Promise<void>;

export function ExportCSV(arg1:string):Promise<void>;

export function FetchApprovedSelection():Promise<types.Selection>;

export function FetchCallEntries(arg1:number):Promise<Array<types.CallEntryDetail>>;

export function FetchCalls():Promise<Array<types.CallSummary>>;

export function FetchRegistration(arg1:number):Promise<types.RegistrationDetail>;

export function FetchRegistrations():Promise<Array<types.Registration>>;

export function FetchRegistrationsByCourseID(arg1:number):Promise<Array<types.Registration>>;

export function FetchRegistrationsBySelectionID(arg1:number):Promise<Array<types.Registration>>;

export function FetchSemesters():Promise<Array<types.Semester>>;

export function FetchWaitlistSelection():Promise<types.Selection>;

export function LoadApprovedSelection(arg1:number,arg2:string):Promise<void>;

export function LoadWaitlistSelection(arg1:number,arg2:string):Promise<void>;

export function OpenCall(arg1:number):Promise<void>;

export function OpenFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PreviewCall():Promise<types.CallPlan>;

export function ReopenSemester(arg1:number):Promise<void>;

export function Restore(arg1:string):Promise<void>;

export function SaveFileDialog(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SetCallEntryOutcome(arg1:number,arg2:number,arg3:string):Promise<void>;

export function SetWantsPromotion(arg1:number,arg2:number,arg3:boolean):Promise<void>;

export function TeacherPDF(arg1:string,arg2:number,arg3:string):Promise<void>;

export function WebsitePDF(arg1:number,arg2:string,arg3:number,arg4:string):Promise<void>;
