//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Calls = newCallsTable("", "calls", "")

type callsTable struct {
	sqlite.Table

	// Columns
	ID     sqlite.ColumnInteger
	Number sqlite.ColumnInteger
	Status sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CallsTable struct {
	callsTable

	EXCLUDED callsTable
}

// AS creates new CallsTable with assigned alias
func (a CallsTable) AS(alias string) *CallsTable {
	return newCallsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CallsTable with assigned schema name
func (a CallsTable) FromSchema(schemaName string) *CallsTable {
	return newCallsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CallsTable with assigned table prefix
func (a CallsTable) WithPrefix(prefix string) *CallsTable {
	return newCallsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CallsTable with assigned table suffix
func (a CallsTable) WithSuffix(suffix string) *CallsTable {
	return newCallsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCallsTable(schemaName, tableName, alias string) *CallsTable {
	return &CallsTable{
		callsTable: newCallsTableImpl(schemaName, tableName, alias),
		EXCLUDED:   newCallsTableImpl("", "excluded", ""),
	}
}

func newCallsTableImpl(schemaName, tableName, alias string) callsTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		NumberColumn   = sqlite.IntegerColumn("number")
		StatusColumn   = sqlite.StringColumn("status")
		allColumns     = sqlite.ColumnList{IDColumn, NumberColumn, StatusColumn}
		mutableColumns = sqlite.ColumnList{NumberColumn, StatusColumn}
		defaultColumns = sqlite.ColumnList{}
	)

	return callsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:     IDColumn,
		Number: NumberColumn,
		Status: StatusColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
