//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var CallEntries = newCallEntriesTable("", "call_entries", "")

type callEntriesTable struct {
	sqlite.Table

	// Columns
	CallID         sqlite.ColumnInteger
	RegistrationID sqlite.ColumnInteger
	Kind           sqlite.ColumnString
	Semester       sqlite.ColumnInteger
	Outcome        sqlite.ColumnString
	WantsPromotion sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CallEntriesTable struct {
	callEntriesTable

	EXCLUDED callEntriesTable
}

// AS creates new CallEntriesTable with assigned alias
func (a CallEntriesTable) AS(alias string) *CallEntriesTable {
	return newCallEntriesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CallEntriesTable with assigned schema name
func (a CallEntriesTable) FromSchema(schemaName string) *CallEntriesTable {
	return newCallEntriesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CallEntriesTable with assigned table prefix
func (a CallEntriesTable) WithPrefix(prefix string) *CallEntriesTable {
	return newCallEntriesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CallEntriesTable with assigned table suffix
func (a CallEntriesTable) WithSuffix(suffix string) *CallEntriesTable {
	return newCallEntriesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCallEntriesTable(schemaName, tableName, alias string) *CallEntriesTable {
	return &CallEntriesTable{
		callEntriesTable: newCallEntriesTableImpl(schemaName, tableName, alias),
		EXCLUDED:         newCallEntriesTableImpl("", "excluded", ""),
	}
}

func newCallEntriesTableImpl(schemaName, tableName, alias string) callEntriesTable {
	var (
		CallIDColumn         = sqlite.IntegerColumn("call_id")
		RegistrationIDColumn = sqlite.IntegerColumn("registration_id")
		KindColumn           = sqlite.StringColumn("kind")
		SemesterColumn       = sqlite.IntegerColumn("semester")
		OutcomeColumn        = sqlite.StringColumn("outcome")
		WantsPromotionColumn = sqlite.IntegerColumn("wants_promotion")
		allColumns           = sqlite.ColumnList{CallIDColumn, RegistrationIDColumn, KindColumn, SemesterColumn, OutcomeColumn, WantsPromotionColumn}
		mutableColumns       = sqlite.ColumnList{KindColumn, SemesterColumn, OutcomeColumn, WantsPromotionColumn}
		defaultColumns       = sqlite.ColumnList{WantsPromotionColumn}
	)

	return callEntriesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		CallID:         CallIDColumn,
		RegistrationID: RegistrationIDColumn,
		Kind:           KindColumn,
		Semester:       SemesterColumn,
		Outcome:        OutcomeColumn,
		WantsPromotion: WantsPromotionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
