//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Candidates = newCandidatesTable("", "candidates", "")

type candidatesTable struct {
	sqlite.Table

	// Columns
	ID           sqlite.ColumnInteger
	Cpf          sqlite.ColumnString
	Name         sqlite.ColumnString
	SocialName   sqlite.ColumnString
	Birthdate    sqlite.ColumnString
	Sex          sqlite.ColumnString
	MotherName   sqlite.ColumnString
	AddressLine  sqlite.ColumnString
	AddressLine2 sqlite.ColumnString
	HouseNumber  sqlite.ColumnString
	Neighborhood sqlite.ColumnString
	Municipality sqlite.ColumnString
	State        sqlite.ColumnString
	Cep          sqlite.ColumnString
	Email        sqlite.ColumnString
	Phone1       sqlite.ColumnString
	Phone2       sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CandidatesTable struct {
	candidatesTable

	EXCLUDED candidatesTable
}

// AS creates new CandidatesTable with assigned alias
func (a CandidatesTable) AS(alias string) *CandidatesTable {
	return newCandidatesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CandidatesTable with assigned schema name
func (a CandidatesTable) FromSchema(schemaName string) *CandidatesTable {
	return newCandidatesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CandidatesTable with assigned table prefix
func (a CandidatesTable) WithPrefix(prefix string) *CandidatesTable {
	return newCandidatesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CandidatesTable with assigned table suffix
func (a CandidatesTable) WithSuffix(suffix string) *CandidatesTable {
	return newCandidatesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCandidatesTable(schemaName, tableName, alias string) *CandidatesTable {
	return &CandidatesTable{
		candidatesTable: newCandidatesTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newCandidatesTableImpl("", "excluded", ""),
	}
}

func newCandidatesTableImpl(schemaName, tableName, alias string) candidatesTable {
	var (
		IDColumn           = sqlite.IntegerColumn("id")
		CpfColumn          = sqlite.StringColumn("cpf")
		NameColumn         = sqlite.StringColumn("name")
		SocialNameColumn   = sqlite.StringColumn("social_name")
		BirthdateColumn    = sqlite.StringColumn("birthdate")
		SexColumn          = sqlite.StringColumn("sex")
		MotherNameColumn   = sqlite.StringColumn("mother_name")
		AddressLineColumn  = sqlite.StringColumn("address_line")
		AddressLine2Column = sqlite.StringColumn("address_line2")
		HouseNumberColumn  = sqlite.StringColumn("house_number")
		NeighborhoodColumn = sqlite.StringColumn("neighborhood")
		MunicipalityColumn = sqlite.StringColumn("municipality")
		StateColumn        = sqlite.StringColumn("state")
		CepColumn          = sqlite.StringColumn("cep")
		EmailColumn        = sqlite.StringColumn("email")
		Phone1Column       = sqlite.StringColumn("phone1")
		Phone2Column       = sqlite.StringColumn("phone2")
		allColumns         = sqlite.ColumnList{IDColumn, CpfColumn, NameColumn, SocialNameColumn, BirthdateColumn, SexColumn, MotherNameColumn, AddressLineColumn, AddressLine2Column, HouseNumberColumn, NeighborhoodColumn, MunicipalityColumn, StateColumn, CepColumn, EmailColumn, Phone1Column, Phone2Column}
		mutableColumns     = sqlite.ColumnList{CpfColumn, NameColumn, SocialNameColumn, BirthdateColumn, SexColumn, MotherNameColumn, AddressLineColumn, AddressLine2Column, HouseNumberColumn, NeighborhoodColumn, MunicipalityColumn, StateColumn, CepColumn, EmailColumn, Phone1Column, Phone2Column}
		defaultColumns     = sqlite.ColumnList{}
	)

	return candidatesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		Cpf:          CpfColumn,
		Name:         NameColumn,
		SocialName:   SocialNameColumn,
		Birthdate:    BirthdateColumn,
		Sex:          SexColumn,
		MotherName:   MotherNameColumn,
		AddressLine:  AddressLineColumn,
		AddressLine2: AddressLine2Column,
		HouseNumber:  HouseNumberColumn,
		Neighborhood: NeighborhoodColumn,
		Municipality: MunicipalityColumn,
		State:        StateColumn,
		Cep:          CepColumn,
		Email:        EmailColumn,
		Phone1:       Phone1Column,
		Phone2:       Phone2Column,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
