//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Courses = newCoursesTable("", "courses", "")

type coursesTable struct {
	sqlite.Table

	// Columns
	ID           sqlite.ColumnInteger
	TimeSlot     sqlite.ColumnString
	QuotaID      sqlite.ColumnInteger
	Seats        sqlite.ColumnInteger
	MinimumScore sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type CoursesTable struct {
	coursesTable

	EXCLUDED coursesTable
}

// AS creates new CoursesTable with assigned alias
func (a CoursesTable) AS(alias string) *CoursesTable {
	return newCoursesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new CoursesTable with assigned schema name
func (a CoursesTable) FromSchema(schemaName string) *CoursesTable {
	return newCoursesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new CoursesTable with assigned table prefix
func (a CoursesTable) WithPrefix(prefix string) *CoursesTable {
	return newCoursesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new CoursesTable with assigned table suffix
func (a CoursesTable) WithSuffix(suffix string) *CoursesTable {
	return newCoursesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newCoursesTable(schemaName, tableName, alias string) *CoursesTable {
	return &CoursesTable{
		coursesTable: newCoursesTableImpl(schemaName, tableName, alias),
		EXCLUDED:     newCoursesTableImpl("", "excluded", ""),
	}
}

func newCoursesTableImpl(schemaName, tableName, alias string) coursesTable {
	var (
		IDColumn           = sqlite.IntegerColumn("id")
		TimeSlotColumn     = sqlite.StringColumn("time_slot")
		QuotaIDColumn      = sqlite.IntegerColumn("quota_id")
		SeatsColumn        = sqlite.IntegerColumn("seats")
		MinimumScoreColumn = sqlite.IntegerColumn("minimum_score")
		allColumns         = sqlite.ColumnList{IDColumn, TimeSlotColumn, QuotaIDColumn, SeatsColumn, MinimumScoreColumn}
		mutableColumns     = sqlite.ColumnList{TimeSlotColumn, QuotaIDColumn, SeatsColumn, MinimumScoreColumn}
		defaultColumns     = sqlite.ColumnList{}
	)

	return coursesTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		TimeSlot:     TimeSlotColumn,
		QuotaID:      QuotaIDColumn,
		Seats:        SeatsColumn,
		MinimumScore: MinimumScoreColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
