//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Quotas = newQuotasTable("", "quotas", "")

type quotasTable struct {
	sqlite.Table

	// Columns
	ID   sqlite.ColumnInteger
	Name sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type QuotasTable struct {
	quotasTable

	EXCLUDED quotasTable
}

// AS creates new QuotasTable with assigned alias
func (a QuotasTable) AS(alias string) *QuotasTable {
	return newQuotasTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new QuotasTable with assigned schema name
func (a QuotasTable) FromSchema(schemaName string) *QuotasTable {
	return newQuotasTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new QuotasTable with assigned table prefix
func (a QuotasTable) WithPrefix(prefix string) *QuotasTable {
	return newQuotasTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new QuotasTable with assigned table suffix
func (a QuotasTable) WithSuffix(suffix string) *QuotasTable {
	return newQuotasTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newQuotasTable(schemaName, tableName, alias string) *QuotasTable {
	return &QuotasTable{
		quotasTable: newQuotasTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newQuotasTableImpl("", "excluded", ""),
	}
}

func newQuotasTableImpl(schemaName, tableName, alias string) quotasTable {
	var (
		IDColumn       = sqlite.IntegerColumn("id")
		NameColumn     = sqlite.StringColumn("name")
		allColumns     = sqlite.ColumnList{IDColumn, NameColumn}
		mutableColumns = sqlite.ColumnList{NameColumn}
		defaultColumns = sqlite.ColumnList{}
	)

	return quotasTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Name: NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
