//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Registrations = newRegistrationsTable("", "registrations", "")

type registrationsTable struct {
	sqlite.Table

	// Columns
	ID                   sqlite.ColumnInteger
	EnrollmentID         sqlite.ColumnString
	CourseID             sqlite.ColumnInteger
	Option               sqlite.ColumnInteger
	LanguagesScore       sqlite.ColumnInteger
	HumanitiesScore      sqlite.ColumnInteger
	NaturalSciencesScore sqlite.ColumnInteger
	MathematicsScore     sqlite.ColumnInteger
	EssayScore           sqlite.ColumnInteger
	CompositeScore       sqlite.ColumnInteger
	Ranking              sqlite.ColumnInteger
	Status               sqlite.ColumnString
	SelectionID          sqlite.ColumnInteger
	CallID               sqlite.ColumnInteger
	CandidateID          sqlite.ColumnInteger
	SemesterID           sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type RegistrationsTable struct {
	registrationsTable

	EXCLUDED registrationsTable
}

// AS creates new RegistrationsTable with assigned alias
func (a RegistrationsTable) AS(alias string) *RegistrationsTable {
	return newRegistrationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RegistrationsTable with assigned schema name
func (a RegistrationsTable) FromSchema(schemaName string) *RegistrationsTable {
	return newRegistrationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RegistrationsTable with assigned table prefix
func (a RegistrationsTable) WithPrefix(prefix string) *RegistrationsTable {
	return newRegistrationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RegistrationsTable with assigned table suffix
func (a RegistrationsTable) WithSuffix(suffix string) *RegistrationsTable {
	return newRegistrationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRegistrationsTable(schemaName, tableName, alias string) *RegistrationsTable {
	return &RegistrationsTable{
		registrationsTable: newRegistrationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newRegistrationsTableImpl("", "excluded", ""),
	}
}

func newRegistrationsTableImpl(schemaName, tableName, alias string) registrationsTable {
	var (
		IDColumn                   = sqlite.IntegerColumn("id")
		EnrollmentIDColumn         = sqlite.StringColumn("enrollment_id")
		CourseIDColumn             = sqlite.IntegerColumn("course_id")
		OptionColumn               = sqlite.IntegerColumn("option")
		LanguagesScoreColumn       = sqlite.IntegerColumn("languages_score")
		HumanitiesScoreColumn      = sqlite.IntegerColumn("humanities_score")
		NaturalSciencesScoreColumn = sqlite.IntegerColumn("natural_sciences_score")
		MathematicsScoreColumn     = sqlite.IntegerColumn("mathematics_score")
		EssayScoreColumn           = sqlite.IntegerColumn("essay_score")
		CompositeScoreColumn       = sqlite.IntegerColumn("composite_score")
		RankingColumn              = sqlite.IntegerColumn("ranking")
		StatusColumn               = sqlite.StringColumn("status")
		SelectionIDColumn          = sqlite.IntegerColumn("selection_id")
		CallIDColumn               = sqlite.IntegerColumn("call_id")
		CandidateIDColumn          = sqlite.IntegerColumn("candidate_id")
		SemesterIDColumn           = sqlite.IntegerColumn("semester_id")
		allColumns                 = sqlite.ColumnList{IDColumn, EnrollmentIDColumn, CourseIDColumn, OptionColumn, LanguagesScoreColumn, HumanitiesScoreColumn, NaturalSciencesScoreColumn, MathematicsScoreColumn, EssayScoreColumn, CompositeScoreColumn, RankingColumn, StatusColumn, SelectionIDColumn, CallIDColumn, CandidateIDColumn, SemesterIDColumn}
		mutableColumns             = sqlite.ColumnList{EnrollmentIDColumn, CourseIDColumn, OptionColumn, LanguagesScoreColumn, HumanitiesScoreColumn, NaturalSciencesScoreColumn, MathematicsScoreColumn, EssayScoreColumn, CompositeScoreColumn, RankingColumn, StatusColumn, SelectionIDColumn, CallIDColumn, CandidateIDColumn, SemesterIDColumn}
		defaultColumns             = sqlite.ColumnList{CallIDColumn, SemesterIDColumn}
	)

	return registrationsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                   IDColumn,
		EnrollmentID:         EnrollmentIDColumn,
		CourseID:             CourseIDColumn,
		Option:               OptionColumn,
		LanguagesScore:       LanguagesScoreColumn,
		HumanitiesScore:      HumanitiesScoreColumn,
		NaturalSciencesScore: NaturalSciencesScoreColumn,
		MathematicsScore:     MathematicsScoreColumn,
		EssayScore:           EssayScoreColumn,
		CompositeScore:       CompositeScoreColumn,
		Ranking:              RankingColumn,
		Status:               StatusColumn,
		SelectionID:          SelectionIDColumn,
		CallID:               CallIDColumn,
		CandidateID:          CandidateIDColumn,
		SemesterID:           SemesterIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
