//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Selections = newSelectionsTable("", "selections", "")

type selectionsTable struct {
	sqlite.Table

	// Columns
	ID          sqlite.ColumnInteger
	Kind        sqlite.ColumnString
	Name        sqlite.ColumnString
	Year        sqlite.ColumnInteger
	Semester    sqlite.ColumnInteger
	Institution sqlite.ColumnString
	Degree      sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type SelectionsTable struct {
	selectionsTable

	EXCLUDED selectionsTable
}

// AS creates new SelectionsTable with assigned alias
func (a SelectionsTable) AS(alias string) *SelectionsTable {
	return newSelectionsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SelectionsTable with assigned schema name
func (a SelectionsTable) FromSchema(schemaName string) *SelectionsTable {
	return newSelectionsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SelectionsTable with assigned table prefix
func (a SelectionsTable) WithPrefix(prefix string) *SelectionsTable {
	return newSelectionsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SelectionsTable with assigned table suffix
func (a SelectionsTable) WithSuffix(suffix string) *SelectionsTable {
	return newSelectionsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSelectionsTable(schemaName, tableName, alias string) *SelectionsTable {
	return &SelectionsTable{
		selectionsTable: newSelectionsTableImpl(schemaName, tableName, alias),
		EXCLUDED:        newSelectionsTableImpl("", "excluded", ""),
	}
}

func newSelectionsTableImpl(schemaName, tableName, alias string) selectionsTable {
	var (
		IDColumn          = sqlite.IntegerColumn("id")
		KindColumn        = sqlite.StringColumn("kind")
		NameColumn        = sqlite.StringColumn("name")
		YearColumn        = sqlite.IntegerColumn("year")
		SemesterColumn    = sqlite.IntegerColumn("semester")
		InstitutionColumn = sqlite.StringColumn("institution")
		DegreeColumn      = sqlite.StringColumn("degree")
		allColumns        = sqlite.ColumnList{IDColumn, KindColumn, NameColumn, YearColumn, SemesterColumn, InstitutionColumn, DegreeColumn}
		mutableColumns    = sqlite.ColumnList{KindColumn, NameColumn, YearColumn, SemesterColumn, InstitutionColumn, DegreeColumn}
		defaultColumns    = sqlite.ColumnList{}
	)

	return selectionsTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:          IDColumn,
		Kind:        KindColumn,
		Name:        NameColumn,
		Year:        YearColumn,
		Semester:    SemesterColumn,
		Institution: InstitutionColumn,
		Degree:      DegreeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
