//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var Semesters = newSemestersTable("", "semesters", "")

type semestersTable struct {
	sqlite.Table

	// Columns
	Number          sqlite.ColumnInteger
	ClosedAfterCall sqlite.ColumnInteger

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
	DefaultColumns sqlite.ColumnList
}

type SemestersTable struct {
	semestersTable

	EXCLUDED semestersTable
}

// AS creates new SemestersTable with assigned alias
func (a SemestersTable) AS(alias string) *SemestersTable {
	return newSemestersTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SemestersTable with assigned schema name
func (a SemestersTable) FromSchema(schemaName string) *SemestersTable {
	return newSemestersTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SemestersTable with assigned table prefix
func (a SemestersTable) WithPrefix(prefix string) *SemestersTable {
	return newSemestersTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SemestersTable with assigned table suffix
func (a SemestersTable) WithSuffix(suffix string) *SemestersTable {
	return newSemestersTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSemestersTable(schemaName, tableName, alias string) *SemestersTable {
	return &SemestersTable{
		semestersTable: newSemestersTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newSemestersTableImpl("", "excluded", ""),
	}
}

func newSemestersTableImpl(schemaName, tableName, alias string) semestersTable {
	var (
		NumberColumn          = sqlite.IntegerColumn("number")
		ClosedAfterCallColumn = sqlite.IntegerColumn("closed_after_call")
		allColumns            = sqlite.ColumnList{NumberColumn, ClosedAfterCallColumn}
		mutableColumns        = sqlite.ColumnList{ClosedAfterCallColumn}
		defaultColumns        = sqlite.ColumnList{ClosedAfterCallColumn}
	)

	return semestersTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		Number:          NumberColumn,
		ClosedAfterCall: ClosedAfterCallColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
